version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=EduManage

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - "./rabbitmq-data:/var/lib/rabbitmq"
    restart: unless-stopped

  api_app:
    build:
      context: .
      dockerfile: Dockerfile_Api
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
      - rabbitmq

  # consumer:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_Consumer
  #   depends_on:
  #     - api_app

  # identity_server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_IdentityServer
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - api_app

volumes:
  redis_data:
