#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["EduManage.Consumer/EduManage.Consumer.csproj", "EduManage.Consumer/"]
COPY ["EduManage.Api.Application/EduManage.Api.Application.csproj", "EduManage.Api.Application/"]
COPY ["EduManage.Api.Domain/EduManage.Api.Domain.csproj", "EduManage.Api.Domain/"]
COPY ["EduManage.Api.Infrastructure/EduManage.Api.Infrastructure.csproj", "EduManage.Api.Infrastructure/"]
RUN dotnet restore "./EduManage.Consumer/./EduManage.Consumer.csproj"
COPY . .
WORKDIR "/src/EduManage.Consumer"
RUN dotnet build "./EduManage.Consumer.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./EduManage.Consumer.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EduManage.Consumer.dll"]